name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: library
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest

      - name: Build Docker image
        run: |
          docker build -t library-management-system .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker tag library-management-system:latest ${{ secrets.DOCKER_USERNAME }}/library-management-system:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/library-management-system:latest

      - name: Deploy to GitHub Pages
        run: |
          docker run -d -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/library-management-system:latest